import { ApprovalStatus } from './models';
export const STUDENTS_DATA = {
  infos: [
    {
        rollNo: '22MA30017',
        name: 'Sohan',
        program: "Master's in CS",
        atRisk: false,
        riskDecs: 'Not at Risk',
        coreCourses: [
          {
            code: '24CS121',
            name: 'Computer Science',
            credits: 4,
            slot: 'B2',
          },
          {
            code: '24CS122',
            name: 'Information Technology',
            credits: 4,
            slot: 'A1',
          },
          { code: '24CS123', name: 'Data Science', credits: 3, slot: 'night' },
          {
            code: '24CS124',
            name: 'Data Analytics',
            credits: 3,
            slot: 'A2',
          },
        ],
        electiveCredits: [
          { code: '24EC201', min: 0, max: 3 },
          { code: '24EC202', min: 0, max: 4 },
          { code: '24EC203', min: 0, max: 5 },
        ],
        approvalStatus: ApprovalStatus.PENDING,
        approvalRemarks: 'good going',
      },
      {
        rollNo: '22MA30018',
        name: 'Monalisa',
        program: "Master's in Electronics",
        atRisk: false,
        riskDecs: 'Not at Risk',
        coreCourses: [
          { code: '24EE201', name: 'Data Science', credits: 3, slot: 'A2' },
          { code: '24EE202', name: 'Mechanical', credits: 3, slot: 'B2' },
          { code: '24EE203', name: 'Civil', credits: 3, slot: 'B1' },
          {
            code: '24EE204',
            name: 'Electronics and Communication',
            credits: 4,
            slot: 'A1',
          },
        ],
        electiveCredits: [
          { code: '24EC201', min: 0, max: 3 },
          { code: '24EC202', min: 0, max: 4 },
          { code: '24EC203', min: 0, max: 5 },
        ],
        approvalStatus: ApprovalStatus.APPROVED,
        approvalRemarks: 'good going',
      },
      {
        rollNo: '22MA30019',
        name: 'Mohan',
        program: "Bachleor's in CS",
        atRisk: true,
        riskDecs: 'At Risk',
        coreCourses: [
          {
            code: '24CE201',
            name: 'Product Management',
            credits: 4,
            slot: 'A2',
          },
          { code: '24CE202', name: 'Mathematics', credits: 3, slot: 'B2' },
          {
            code: '24CE203',
            name: 'Computer Aided Drawings',
            credits: 4,
            slot: 'B2',
          },
          { code: '24CE204', name: 'Mechanial', credits: 2, slot: 'A1' },
        ],
        electiveCredits: [
          { code: '24CE201', min: 0, max: 3 },
          { code: '24CE202', min: 0, max: 4 },
          { code: '24CE203', min: 0, max: 5 },
        ],
        approvalStatus: ApprovalStatus.PENDING,
        approvalRemarks: 'Not Good Going',
      },
      {
        rollNo: '22MA30020',
        name: 'Ananya',
        program: "Master's in Data Analytics",
        atRisk: true,
        riskDecs: 'At Risk',
        coreCourses: [
          {
            code: '24CE201',
            name: 'Product Management',
            credits: 4,
            slot: 'A2',
          },
          { code: '24CE202', name: 'Mathematics', credits: 3, slot: 'B1' },
          {
            code: '24CE203',
            name: 'Computer Aided Drawings',
            credits: 4,
            slot: 'B2',
          },
          { code: '24CE204', name: 'Mechanial', credits: 2, slot: 'B2' },
        ],
        electiveCredits: [
          { code: '24CE201', min: 0, max: 3 },
          { code: '24CE202', min: 0, max: 4 },
          { code: '24CE203', min: 0, max: 5 },
        ],
        approvalStatus: ApprovalStatus.APPROVED,
        approvalRemarks: 'Need more efforts',
      },
      {
        rollNo: '22MA30021',
        name: 'Shanaya',
        program: "Bachelor's in IT",
        atRisk: false,
        riskDecs: 'Not at Risk',
        coreCourses: [
          {
            code: '24CE201',
            name: 'Product Management',
            credits: 4,
            slot: 'B2',
          },
          { code: '24CE202', name: 'Mathematics', credits: 3, slot: 'B1' },
          {
            code: '24CE203',
            name: 'Computer Aided Drawings',
            credits: 4,
            slot: 'A1',
          },
          { code: '24CE204', name: 'Mechanial', credits: 2, slot: 'B2' },
        ],
        electiveCredits: [
          { code: '24CE201', min: 0, max: 3 },
          { code: '24CE202', min: 0, max: 4 },
          { code: '24CE203', min: 0, max: 5 },
        ],
        approvalStatus: ApprovalStatus.PENDING,
        approvalRemarks: 'Very Good going',
      },
      {
        rollNo: '22MA30022',
        name: 'Sohan',
        program: "Master's in CS",
        atRisk: false,
        riskDecs: 'Not at Risk',
        coreCourses: [
          {
            code: '24CS121',
            name: 'Computer Science',
            credits: 4,
            slot: 'B1',
          },
          {
            code: '24CS122',
            name: 'Information Technology',
            credits: 4,
            slot: 'A1',
          },
          { code: '24CS123', name: 'Data Science', credits: 3, slot: 'B1' },
          {
            code: '24CS124',
            name: 'Data Analytics',
            credits: 3,
            slot: 'B2',
          },
        ],
        electiveCredits: [
          { code: '24EC201', min: 0, max: 3 },
          { code: '24EC202', min: 0, max: 4 },
          { code: '24EC203', min: 0, max: 5 },
        ],
        approvalStatus: ApprovalStatus.APPROVED,
        approvalRemarks: 'good going',
      },
      {
        rollNo: '22MA30023',
        name: 'Monal',
        program: "Master's in Electronics",
        atRisk: false,
        riskDecs: 'Not at Risk',
        coreCourses: [
          { code: '24EE201', name: 'Data Science', credits: 3, slot: 'B2' },
          { code: '24EE202', name: 'Mechanical', credits: 3, slot: 'A2' },
          { code: '24EE203', name: 'Civil', credits: 3, slot: 'A1' },
          {
            code: '24EE204',
            name: 'Electronics and Communication',
            credits: 4,
            slot: 'A2',
          },
        ],
        electiveCredits: [
          { code: '24EC201', min: 0, max: 3 },
          { code: '24EC202', min: 0, max: 4 },
          { code: '24EC203', min: 0, max: 5 },
        ],
        approvalStatus: ApprovalStatus.APPROVED,
        approvalRemarks: 'good going',
      },
      {
        rollNo: '22MA30024',
        name: 'Mohan',
        program: "Bachleor's in CS",
        atRisk: true,
        riskDecs: 'At Risk',
        coreCourses: [
          {
            code: '24CE201',
            name: 'Product Management',
            credits: 4,
            slot: 'A2',
          },
          { code: '24CE202', name: 'Mathematics', credits: 3, slot: 'A2' },
          {
            code: '24CE203',
            name: 'Computer Aided Drawings',
            credits: 4,
            slot: 'A1',
          },
          { code: '24CE204', name: 'Mechanial', credits: 2, slot: 'B2' },
        ],
        electiveCredits: [
          { code: '24CE201', min: 0, max: 3 },
          { code: '24CE202', min: 0, max: 4 },
          { code: '24CE203', min: 0, max: 5 },
        ],
        approvalStatus: ApprovalStatus.PENDING,
        approvalRemarks: 'Not Good Going',
      },
      {
        rollNo: '22MA30025',
        name: 'Anika',
        program: "Master's in Data Analytics",
        atRisk: true,
        riskDecs: 'At Risk',
        coreCourses: [
          {
            code: '24CE201',
            name: 'Product Management',
            credits: 4,
            slot: 'B1',
          },
          { code: '24CE202', name: 'Mathematics', credits: 3, slot: 'B1' },
          {
            code: '24CE203',
            name: 'Computer Aided Drawings',
            credits: 4,
            slot: 'A1',
          },
          { code: '24CE204', name: 'Mechanial', credits: 2, slot: 'B2' },
        ],
        electiveCredits: [
          { code: '24CE201', min: 0, max: 3 },
          { code: '24CE202', min: 0, max: 4 },
          { code: '24CE203', min: 0, max: 5 },
        ],
        approvalStatus: ApprovalStatus.APPROVED,
        approvalRemarks: 'Need more efforts',
      },
      {
        rollNo: '22MA30026',
        name: 'Shantanu',
        program: "Bachelor's in IT",
        atRisk: false,
        riskDecs: 'Not at Risk',
        coreCourses: [
          {
            code: '24CE201',
            name: 'Product Management',
            credits: 4,
            slot: 'A2',
          },
          { code: '24CE202', name: 'Mathematics', credits: 3, slot: 'A2' },
          {
            code: '24CE203',
            name: 'Computer Aided Drawings',
            credits: 4,
            slot: 'A2',
          },
          { code: '24CE204', name: 'Mechanial', credits: 2, slot: 'B2' },
        ],
        electiveCredits: [
          { code: '24CE201', min: 0, max: 3 },
          { code: '24CE202', min: 0, max: 4 },
          { code: '24CE203', min: 0, max: 5 },
        ],
        approvalStatus: ApprovalStatus.PENDING,
        approvalRemarks: 'Very Good going',
      }
  ],
};
